### ISSUE TITLE
Build failed due to failed import

### ISSUE THREAD

**Issue by nkansal96** [ucladevx/governor-acm#3]
Running `npm run build` results in the following output:

```
Hash: 5e63fc21ddc4cc4c8838
Version: webpack 2.4.1
Time: 31037ms
        Asset    Size  Chunks                    Chunk Names
build/main.js  400 kB       0  [emitted]  [big]  main
   [5] ../~/react/react.js 55 bytes {0} [built]
  [94] ../~/react-redux/es/index.js 713 bytes {0} [built]
 [148] ../~/react-router-redux/es/index.js 2.01 kB {0} [built]
 [149] ./reducers/index.js 1.05 kB {0} [built]
 [222] ../~/babel-polyfill/lib/index.js 833 bytes {0} [built]
 [223] ../~/react-dom/index.js 58 bytes {0} [built]
 [224] ../~/react-router-dom/es/index.js 2.21 kB {0} [built]
 [227] ./containers/about.js 2.65 kB {0} [built]
 [228] ./containers/home.js 4.02 kB {0} [built]
 [229] ./main.scss 1.28 kB {0} [built] [failed] [1 error]
 [512] ../~/react-router-dom/es/BrowserRouter.js 3.01 kB {0} [built]
 [522] ../~/react-router-dom/es/matchPath.js 256 bytes {0} [built]
 [523] ../~/react-router-dom/es/withRouter.js 257 bytes {0} [built]
 [524] ../~/react-router-redux/es/ConnectedRouter.js 3.36 kB {0} [built]
 [565] ./main.js 3.31 kB {0} [built]
    + 552 hidden modules

ERROR in ./main.scss
Module build failed:
@import "components/Dashboard/style";
^
      File to import not found or unreadable: components/Dashboard/style.
Parent style sheet: stdin
      in /var/www/membership/working/src/main.scss (line 2, column 1)
 @ ./main.js 5:0-20

ERROR in ./main.scss
Module build failed: ModuleBuildError: Module build failed:
@import "components/Dashboard/style";
^
      File to import not found or unreadable: components/Dashboard/style.
Parent style sheet: stdin
      in /var/www/membership/working/src/main.scss (line 2, column 1)
    at runLoaders (/var/www/membership/working/node_modules/webpack/lib/NormalModule.js:192:19)
    at /var/www/membership/working/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/membership/working/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/membership/working/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/var/www/membership/working/node_modules/sass-loader/lib/loader.js:57:13)
    at Object.<anonymous> (/var/www/membership/working/node_modules/async/dist/async.js:2262:31)
    at apply (/var/www/membership/working/node_modules/async/dist/async.js:20:25)
    at Object.<anonymous> (/var/www/membership/working/node_modules/async/dist/async.js:56:12)
    at Object.callback (/var/www/membership/working/node_modules/async/dist/async.js:944:16)
    at options.error (/var/www/membership/working/node_modules/node-sass/lib/index.js:294:32)

ERROR in /var/www/membership/working/node_modules/extract-text-webpack-plugin/loader.js??ref--0-0!/var/www/membership/working/node_modules/css-loader/index.js??ref--0-1!/var/www/membership/working/node_modules/sass-loader/lib/loader.js!/var/www/membership/working/src/main.scss doesn't export content
Child extract-text-webpack-plugin:
       [0] ../~/css-loader?{"minimize":true}!../~/sass-loader/lib/loader.js!./main.scss 258 bytes {0} [built] [failed] [1 error]

    ERROR in ../~/css-loader?{"minimize":true}!../~/sass-loader/lib/loader.js!./main.scss
    Module build failed:
    @import "components/Dashboard/style";
    ^
          File to import not found or unreadable: components/Dashboard/style.
    Parent style sheet: stdin
          in /var/www/membership/working/src/main.scss (line 2, column 1)
```

This appears to be due to the fact that the actual file locations is `src/components/`**`DashBoard`**`/style` instead of `src/components/`**`Dashboard`**`/style` as requested.

The output of `tree src` is as follows:
```
.
|-- components
|   |-- DashBoard
|   |   |-- index.js
|   |   `-- style.scss
|   |-- DaysContainer
|   |   `-- index.js
|   |-- EventsList
|   |   `-- index.js
|   |-- Sidebar
|   |   |-- checkin.js
|   |   |-- index.js
|   |   |-- leaderboard.js
|   |   |-- organization.js
|   |   |-- pointsBar.js
|   |   |-- points.js
|   |   |-- profilePicture.js
|   |   |-- settings.js
|   |   |-- style.scss
|   |   `-- userName.js
|   `-- SingleDay
|       `-- index.js
|-- config.js
|-- containers
|   |-- about.js
|   `-- home.js
|-- main.js
|-- main.scss
|-- reducers
|   |-- health.js
|   `-- index.js
|-- styles
|   `-- vars.scss
`-- view
    |-- navbar.js
    `-- Sidebar
        `-- index.js
```

**Comment by ramsgoli** [comment]
Hey Nikhil, can't replicate this issue.
Running `npm run build` results in the following for me:

```npm run build

> reactant@0.1.0 build /Users/ramgoli/projects/governor-acm
> webpack -p --progress --color

Hash: d8b50d8568e2f6a40856                                                               
Version: webpack 2.4.1
Time: 19951ms
         Asset     Size  Chunks                    Chunk Names
 build/main.js   399 kB       0  [emitted]  [big]  main
build/main.css  1.19 kB       0  [emitted]         main
   [5] ../~/react/react.js 55 bytes {0} [built]
  [94] ../~/react-redux/es/index.js 713 bytes {0} [built]
 [147] ./config.js 252 bytes {0} [built]
 [148] ../~/react-router-redux/es/index.js 2.01 kB {0} [built]
 [149] ./reducers/index.js 1.05 kB {0} [built]
 [222] ../~/babel-polyfill/lib/index.js 833 bytes {0} [built]
 [223] ../~/react-dom/index.js 58 bytes {0} [built]
 [224] ../~/react-router-dom/es/index.js 2.21 kB {0} [built]
 [227] ./containers/about.js 2.65 kB {0} [built]
 [228] ./containers/home.js 4.02 kB {0} [built]
 [229] ./main.scss 41 bytes {0} [built]
 [521] ../~/react-router-dom/es/Switch.js 253 bytes {0} [built]
 [545] ../~/redux-thunk/lib/index.js 529 bytes {0} [built]
 [549] ../~/regenerator-runtime/runtime.js 24.2 kB {0} [built]
 [565] ./main.js 3.31 kB {0} [built]
    + 557 hidden modules
Child extract-text-webpack-plugin:
       [0] ../~/css-loader/lib/css-base.js 2.21 kB {0} [built]
       [1] ../~/base64-js/index.js 3.5 kB {0} [built]
       [2] ../~/buffer/index.js 48.8 kB {0} [built]
       [3] ../~/buffer/~/isarray/index.js 146 bytes {0} [built]
       [4] ../~/ieee754/index.js 2.09 kB {0} [built]
       [5] ../~/webpack/buildin/global.js 823 bytes {0} [built]
       [6] ../~/css-loader?{"minimize":true}!../~/sass-loader/lib/loader.js!./main.scss 1.36 kB {0} [built]
```

I fixed the typo, but I'm not sure why your output is different from mine..

**Comment by nkansal96** [comment]
Are you using macOS? I think macOS uses a case-insensitive file system, whereas ext4 (Linux filesystem) is case-sensitive.

**Comment by ramsgoli** [comment]
Yes I am. That is unfortunate... I'll keep an eye out for future case-naming issues as well since I'm developing on macOS
